services:
  web:
    image: terrastories/terrastories:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - 80:3000
      - 3000:3000
    environment:
      - RAILS_ENV=offline
      - HOST_HOSTNAME=terrastories.local
      - TILESERVER_URL=${TILESERVER_URL-http://terrastories.local:8080/styles/terrastories-map/style.json}
      - DATABASE_URL=postgresql://terrastories:terrastories@db:5432/terrastories
    volumes:
      - ./media:/media
      - ./import:/api/import/media

  tileserver:
    restart: unless-stopped
    image: terrastories/terrastories-map:latest
    ports:
      - 8080:8080
    ### UNCOMMENT THE NEXT TWO LINES IF YOU WANT TO USE A CUSTOM MAP PACKAGE
    # volumes:
    #   - ./map/data:/data:ro

  db:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=terrastories
      - POSTGRES_PASSWORD=terrastories
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - terrastories_db:/var/lib/postgresql/data

volumes:
  terrastories_db: