services:
  web:
    image: terrastories/terrastories:latest
    ports:
      - 80:3000
    env_file: .env
    environment:
      - RAILS_ENV=offline
      - HOST_HOSTNAME=${HOST_HOSTNAME-terrastories.local}
      - OFFLINE_MAP_STYLE=${OFFLINE_MAP_STYLE-terrastories-map}
      - DATABASE_URL=${DATABASE_URL-postgresql://terrastories:terrastories@db:5432/terrastories}
    volumes:
      - ./media:/media
      - ./import:/api/import/media
      - ./map:/api/public/map:ro

  db:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=terrastories
      - POSTGRES_PASSWORD=terrastories
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - terrastories_db:/var/lib/postgresql/data

volumes:
  terrastories_db: