services:
  web:
    image: terrastories/terrastories:latest
    depends_on:
      - db
    ports:
      - 80:3000
      - 3000:3000
    environment:
      - RAILS_ENV=offline
      - HOST_HOSTNAME=terrastories.local
      - DEFAULT_MAP_PACKAGE=${DEFAULT_MAP_PACKAGE-terrastories-map}
      - DATABASE_URL=postgresql://terrastories:terrastories@db:5432/terrastories
    volumes:
      - ./media:/media
      - ./import:/api/import/media

  db:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=terrastories
      - POSTGRES_PASSWORD=terrastories
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - terrastories_db:/var/lib/postgresql/data

volumes:
  terrastories_db: